Vacation/Workers/Controllers/HolidaysController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DataAccessLayer.Repository;
using DataAccessLayer.Models;
using Workers.Models_View;
using System.Globalization;
using Microsoft.AspNetCore.Authorization;

namespace Workers.Controllers
{
    [Authorize]
    [Route("[controller]/[action]/{holidaysId?}")]
    public class HolidaysController : Controller
    {
        public IEFGenericRepository<Team> TeamRepository { get; set; }

        public IEFGenericRepository<Person> Personrepository { get; set; }
        public IEFGenericRepository<Weekend> Weekendrepository { get; set; }

        public HolidaysController(IEFGenericRepository<Person> personrepository, IEFGenericRepository<Team> teamRepository,IEFGenericRepository<Weekend>weekendpository)
        {
            Personrepository = personrepository;
            TeamRepository = teamRepository;
            Weekendrepository = weekendpository;
        }
       /* [Route("/HolydaysView")]*/
        public IActionResult HolydaysView()
        {
           IEnumerable<Weekend> weekend = Weekendrepository.Get();
           return View(weekend);
        }
        /* [Route("/CreateHolydays")]*/
        [Authorize(Roles = "admin")]
        public IActionResult CreateHolydays() {

            //  return Redirect("/HolydaysView");
            return View();
        }
        public partial class DateRangePickerController : Controller
        {

            public IActionResult Index()
            {
                return View();
            }
        }
        /*     [Route("/CreateNewHolydays")]*/
        [Authorize(Roles = "admin")]
        public IActionResult CreateNewHolydays(Holydays newweekend)
        {
            Weekend weekend = new Weekend();
            weekend.Id = Guid.NewGuid();

            weekend.startDate = DateTime.ParseExact(newweekend.startDay, "M/d/yyyy", CultureInfo.InvariantCulture);
            weekend.EndDate = weekend.startDate.AddDays(newweekend.AddDays-1);
            weekend.Name = newweekend.Name;
            Weekendrepository.Create(weekend);
            return Redirect("/Holidays/HolydaysView");
        }
  
        public IActionResult ChnageHolydays(Guid holidaysId, Holydays Updateholydays)
        {
            Weekend weekend = Weekendrepository.FindById(holidaysId);
            weekend.startDate = DateTime.ParseExact(Updateholydays.startDay, "M/d/yyyy", CultureInfo.InvariantCulture);
            weekend.EndDate = weekend.startDate.AddDays(Updateholydays.AddDays - 1);
            weekend.Name = Updateholydays.Name;
            Weekendrepository.Update(weekend);
         
            return Redirect("/Holidays/HolydaysView");
        }
    
        /*  [Route("/DeleteHolyDay/{holidaysId}")]*/
        [Authorize(Roles = "admin")]
        public IActionResult DeleteHolyDay(Guid holidaysId)
        {
            Weekend weekend = Weekendrepository.FindById(holidaysId);
            Weekendrepository.Remove(weekend);
            return Redirect("/Holidays/HolydaysView");
        }

        //[Route("Holidays/ChangeWeekend/{holidaysId}")]
        [Authorize(Roles = "admin")]
        public IActionResult ChangeWeekend(Guid holidaysId)
        {
            Weekend weekend = Weekendrepository.FindById(holidaysId);
            ViewBag.holidaysId = holidaysId;
            Holydays holydays = new Holydays();
            holydays.Name = weekend.Name;
            ViewBag.holidaysId = holidaysId;
            holydays.startDay = weekend.startDate.ToString("MM/dd/yyyy", CultureInfo.InvariantCulture);
            holydays.AddDays = (weekend.EndDate-weekend.startDate).Days+1;
            return View(holydays);
        }

    }
}

Vacation/Workers/Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Workers.ModelsView;
using Workers.Models;
using Microsoft.AspNetCore.Authorization;
using DataAccessLayer.Repository;
using DataAccessLayer.Models;
using System.Text.RegularExpressions;
namespace Workers.Controllers
{
    [Route("[controller]/[action]")]
    [Authorize(Roles = "admin")]
    public class RolesController : Controller
    {
        RoleManager<IdentityRole> _roleManager;
        UserManager<UserAuthentication> _userManager;
        public IEFGenericRepository<Person> PersonRepository { get; set; }
        public RolesController(RoleManager<IdentityRole> roleManager, UserManager<UserAuthentication> userManager, IEFGenericRepository<Person> personreposito)
        {
            PersonRepository = personreposito;
            _roleManager = roleManager;
            _userManager = userManager;
        }
        public IActionResult Index()
        {
            return View(_roleManager.Roles.ToList());
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(string name)
        {
            if (!string.IsNullOrEmpty(name))
            {
                IdentityResult result = await _roleManager.CreateAsync(new IdentityRole(name));
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(name);
        }
        public async Task<IActionResult> Delete(string id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);
            if (role != null)
            {
                IdentityResult result = await _roleManager.DeleteAsync(role);
            }
            return RedirectToAction("Index");

        }
        public IActionResult UserList()
        {
           return View(_userManager.Users.ToList());
        }
        public async Task<IActionResult> Edit(string userId)
        {
       
            UserAuthentication userAuthentication = await _userManager.FindByIdAsync(userId);
            if (userAuthentication != null)
            {
             
                var userRoles = await _userManager.GetRolesAsync(userAuthentication);
                var allRoles = _roleManager.Roles.ToList();
                ChangeRoleViewModel model = new ChangeRoleViewModel
                {
                    UserId = userAuthentication.Id,
                    UserEmail = userAuthentication.Email,
                    UserRoles = userRoles,
                    AllRoles = allRoles
                };
                return View(model);
            }

            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> Edit(string userId, List<string> roles)
        {
            UserAuthentication userAuthentication = await _userManager.FindByIdAsync(userId);
            if (userAuthentication != null)
            {
                var userRoles = await _userManager.GetRolesAsync(userAuthentication);
                var allRoles = _roleManager.Roles.ToList();
                var addedRoles = roles.Except(userRoles);
            
                var removedRoles = userRoles.Except(roles);

                await _userManager.AddToRolesAsync(userAuthentication, addedRoles);

                await _userManager.RemoveFromRolesAsync(userAuthentication, removedRoles);

                return RedirectToAction("UserList");
            }

            return NotFound();
        }
  
        public async Task<IActionResult> AddPerson(string userId)
        {       
            ViewBag.People = PersonRepository.Get().ToList(); 
            UserAuthentication userAuthentication = await _userManager.FindByIdAsync(userId);
            return View(userAuthentication);
        }

       [HttpPost]
        public async Task<IActionResult> AddPersons(string personId)
        {
            string[] employeeId =Splitstr( personId, "+/+");
            Person person = PersonRepository.FindById(Guid.Parse(employeeId[0]));
            UserAuthentication userAuthentication = await _userManager.FindByIdAsync(employeeId[1]);
            userAuthentication.personId = person.Id;

            var userRoles = await _userManager.GetRolesAsync(userAuthentication);
            // получаем все роли

            var AddRoles= userRoles;
            AddRoles.Add("employee");
            await _userManager.AddToRoleAsync(userAuthentication, "employee");
          
            return RedirectToAction("UserList");
        }
       public  string[] Splitstr( string str, string splitter)
        {
            return str.Split(new[] { splitter }, StringSplitOptions.None);
        }
    }
    
}

Vacation/Workers/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Authorization
@inject DataAccessLayer.CountVacation CountVAcation
@inject IAuthorizationService AuthorizationService
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Workers</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />

    </environment>
 
    <script src="~/lib/momentjs/locale/de-CH.js"></script>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    @*<script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>*@
    <link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="" asp-action="" class="navbar-brand">Company</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

                    <li><a asp-area="" asp-controller="" asp-action="">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Workers">Workers</a></li>
                    @*<li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>*@
                    <li><a asp-area="" asp-controller="Holidays" asp-action="HolydaysView">Holydays</a></li>
                    @*@if (@User.Identity. == "admin")*@
                    @if (User.IsInRole("admin"))
                    {
                        <li><a asp-area="" asp-controller="Roles" asp-action="Index">Change roles</a></li>
                        <li><a asp-area="" asp-controller="Home" asp-action="NewVacation"> New vacations
                            @if(CountVAcation.GetNumbervacation()!=0){
                                <span class="badge" style="margin-bottom:3px;">@CountVAcation.GetNumbervacation()</span>
                            }</a>
                    </li>
                        <li><a asp-area="" asp-controller="Home" asp-action="Index">Team</a></li>
                    }
                    @if (User.IsInRole("employee"))
                    {
                        <li><a asp-area="" asp-action="Mydata" asp-controller="Home">My data</a></li>

                    }

                    @if (User.Identity.IsAuthenticated)
                    {

                        <li>
                            <form method="post" asp-controller="Account" asp-action="Logout">
                                <input style="margin-left: 18em;margin-top:10px; " type="submit" class="btn btn-primary" value="Logout" />
                            </form>
                        </li>
                        <li>
                            <h5 style="color:azure;margin-left:2em; margin-top:17px; ">@User.Identity.Name</h5>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - Workers</p>
        </footer>
    </div>

    <environment include="Development">
        @*<script src="~/lib/jquery/dist/jquery.js"></script>*@
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>