Vacation/Workers/Controllers/HolidaysController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DataAccessLayer.Repository;
using DataAccessLayer.Models;
using Workers.Models_View;
using System.Globalization;
using Microsoft.AspNetCore.Authorization;

namespace Workers.Controllers
{
    [Authorize]
    [Route("[controller]/[action]/{holidaysId?}")]
    public class HolidaysController : Controller
    {
        public IEFGenericRepository<Team> TeamRepository { get; set; }

        public IEFGenericRepository<Person> Personrepository { get; set; }
        public IEFGenericRepository<Weekend> Weekendrepository { get; set; }

        public HolidaysController(IEFGenericRepository<Person> personrepository, IEFGenericRepository<Team> teamRepository,IEFGenericRepository<Weekend>weekendpository)
        {
            Personrepository = personrepository;
            TeamRepository = teamRepository;
            Weekendrepository = weekendpository;
        }
       /* [Route("/HolydaysView")]*/
        public IActionResult HolydaysView()
        {
           IEnumerable<Weekend> weekend = Weekendrepository.Get();
           return View(weekend);
        }
        /* [Route("/CreateHolydays")]*/
        [Authorize(Roles = "admin")]
        public IActionResult CreateHolydays() {

            //  return Redirect("/HolydaysView");
            return View();
        }
        public partial class DateRangePickerController : Controller
        {

            public IActionResult Index()
            {
                return View();
            }
        }
        /*     [Route("/CreateNewHolydays")]*/
        [Authorize(Roles = "admin")]
        public IActionResult CreateNewHolydays(Holydays newweekend)
        {
            Weekend weekend = new Weekend();
            weekend.Id = Guid.NewGuid();

            weekend.startDate = DateTime.ParseExact(newweekend.startDay, "M/d/yyyy", CultureInfo.InvariantCulture);
            weekend.EndDate = weekend.startDate.AddDays(newweekend.AddDays-1);
            weekend.Name = newweekend.Name;
            Weekendrepository.Create(weekend);
            return Redirect("/Holidays/HolydaysView");
        }
  
        public IActionResult ChnageHolydays(Guid holidaysId, Holydays Updateholydays)
        {
            Weekend weekend = Weekendrepository.FindById(holidaysId);
            weekend.startDate = DateTime.ParseExact(Updateholydays.startDay, "M/d/yyyy", CultureInfo.InvariantCulture);
            weekend.EndDate = weekend.startDate.AddDays(Updateholydays.AddDays - 1);
            weekend.Name = Updateholydays.Name;
            Weekendrepository.Update(weekend);
         
            return Redirect("/Holidays/HolydaysView");
        }
    
        /*  [Route("/DeleteHolyDay/{holidaysId}")]*/
        [Authorize(Roles = "admin")]
        public IActionResult DeleteHolyDay(Guid holidaysId)
        {
            Weekend weekend = Weekendrepository.FindById(holidaysId);
            Weekendrepository.Remove(weekend);
            return Redirect("/Holidays/HolydaysView");
        }

        //[Route("Holidays/ChangeWeekend/{holidaysId}")]
        [Authorize(Roles = "admin")]
        public IActionResult ChangeWeekend(Guid holidaysId)
        {
            Weekend weekend = Weekendrepository.FindById(holidaysId);
            ViewBag.holidaysId = holidaysId;
            Holydays holydays = new Holydays();
            holydays.Name = weekend.Name;
            ViewBag.holidaysId = holidaysId;
            holydays.startDay = weekend.startDate.ToString("MM/dd/yyyy", CultureInfo.InvariantCulture);
            holydays.AddDays = (weekend.EndDate-weekend.startDate).Days+1;
            return View(holydays);
        }

    }
}

Vacation/Workers/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using DataAccessLayer.Models;
using DataAccessLayer.Repository;
using Microsoft.AspNetCore.Mvc;
using Workers.Models;
using Microsoft.AspNetCore.Authorization;
using Workers.Models_View;
using System.Globalization;
using DataAccessLayer;
using Microsoft.AspNetCore.Identity;
using System.Security.Claims;
namespace Workers.Controllers
{

    [Route("[controller]/[action]")]
    [Authorize]
    public class HomeController : Controller
    {
        public IEFGenericRepository<Team> TeamRepository { get; set; }
        public IEFGenericRepository<Person> PersonRepository { get; set; }
        public IEFGenericRepository<HistoryAddingDays> HistoryAddingDaysRepository { get; set; }
        public IEFGenericRepository<Vacation> Vacationrepository { get; set; }
        private readonly UserManager<UserAuthentication> _userManager;
        private readonly SignInManager<UserAuthentication> _signInManager;
        public IEFGenericRepository<Weekend> WeekendRepository { get; set; }
        public CountVacation CountVacation { get; set; }
        public HomeController(UserManager<UserAuthentication> userManager, SignInManager<UserAuthentication> signInManager,IEFGenericRepository<Team> teamrepository, IEFGenericRepository<Person> personrepository,IEFGenericRepository<HistoryAddingDays>historyAddingDaysrepository,IEFGenericRepository<Weekend> wekendRepository,IEFGenericRepository<Vacation> vacationRepository,CountVacation countVacation)
        {
            CountVacation = countVacation;
            _userManager = userManager;
            _signInManager = signInManager;
            Vacationrepository = vacationRepository;
            TeamRepository = teamrepository;
            PersonRepository = personrepository;
            HistoryAddingDaysRepository = historyAddingDaysrepository;
            WeekendRepository = wekendRepository;
        }


        public IActionResult Index()
        {
            IEnumerable<Team> Teams = TeamRepository.Get();
            ViewBag.NewVacation = Vacationrepository.Count(x => !x.ConfirmedVacation);
            return View(Teams);
        }
        [Route("[controller]/[action]")]
        /* [Route("/Workers")]*/
        public IActionResult Workers()
        {
            ViewData["Message"] = "Your application description page.";
            ViewBag.Teams = TeamRepository.Get();
            List<Person> people = PersonRepository.Get().ToList();
            if (people.Count == 0)
                ViewBag.NextYear = false;
            else {
                if (HistoryAddingDaysRepository.Get().Count() == 0)
                {
                    ViewBag.NextYear = true;
                }
                else if (HistoryAddingDaysRepository.Get(p => p.Year == people[0].Year ) == null)
                {
                    ViewBag.NextYear = true;
                }
                else {
                    ViewBag.NextYear = false;
                }
            }
            return View(PersonRepository.IncludeGet(p => p.Team));
        }
        /*[Route("/{TeamName}")]
        public IActionResult TeamIndex()
        {
            ViewData["Message"] = "Your Team page.";

            return View();
        }*/
        /*        [Authorize]*/
        // [Authorize(Roles = "admin")]
        [Route("[controller]/[action]")]
        /*    [Route("/AddnewTeam")]*/
        public IActionResult AddnewTeam()
        {
            ViewData["Message"] = "Add Team  page.";

            return View();
        }
        /*       [Authorize]*/
        /* [Route("/CreatenewTeam")]*/
        // [Authorize(Roles = "admin")]
        [Route("[controller]/[action]")]
        [HttpPost]
        public IActionResult CreatenewTeam(Team newTeam)
        {
            Team team = new Team();
            team.MinNumberWorkers = newTeam.MinNumberWorkers;
            team.TeamName = newTeam.TeamName;
            team.Id = Guid.NewGuid();
            if (team.MinNumberWorkers > 20 || team.MinNumberWorkers < 0)
                return Redirect("~/CreatenewTeam");
            TeamRepository.Create(newTeam);

            return Redirect("~/");
        }
        //  [Authorize]
        [Route("[controller]/[action]")]
        /* [Route("/Contact")]*/
        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";
            return View();
        }
        [Route("[controller]/[action]")]
        public IActionResult Privacy()
        {
            return View();
        }
        /*        [Authorize]*/
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        [Authorize(Roles ="admin")]
        [Route("[controller]/[action]")]

        public IActionResult NextYear()
        {
            List<Person> people = PersonRepository.IncludeGet(p => p.Team).ToList();
            HistoryAddingDays historyAddingDays = new HistoryAddingDays();
            if (people[0] == null)
                return Redirect("/Home/Workers/Home/Workers");
            historyAddingDays.Year = people[0].Year;
            historyAddingDays.NumberAddDays = 17;
            historyAddingDays.Id = Guid.NewGuid();
            historyAddingDays.CheckAddDays = true;
            HistoryAddingDaysRepository.Create(historyAddingDays);
            foreach (Person person in people)
            {
                Person newperson = person;
                person.Year ++;
                newperson.Days += 18;
                PersonRepository.Update(newperson);
            }
            IEnumerable<Weekend> weekends = WeekendRepository.Get(p => p.startDate.Year == DateTime.Now.Year);
            List<Weekend> NewWeekends = new List<Weekend>();
            Weekend Updateweekend = new Weekend();
            foreach (Weekend weekend in weekends)
            {
                Updateweekend.Id = Guid.NewGuid();
                Updateweekend.Name = weekend.Name;
                Updateweekend.startDate= weekend.startDate.AddYears(1);
                Updateweekend.EndDate  =weekend.EndDate.AddYears(1);
                WeekendRepository.Create(Updateweekend);
                NewWeekends.Add(weekend);
            }
             
            return View(NewWeekends);
        }
        [Route("/")]
        public IActionResult ShowVacationAll()
        {
            List<PersonView> personViews = new List<PersonView>();
            int i = 0;
            IEnumerable<Person> people= PersonRepository.IncludeGet(p => p.HolyDays).Where(p => p.HolyDays.Count > 0);
            int numColors = people.Count();
            var colors =GetColors(numColors) ;
            foreach (Person person in people)
            {
                personViews.Add(new PersonView
                {
                    PersonId = person.Id,
                    Name = person.Name,
                    LastName = person.LastName,
                    TeamName = PersonRepository.IncludeGet(p => p.Team).FirstOrDefault(x => x.Team.Id == person.TeamId).Team.TeamName,
                    backgroundColor = colors[i]

                }) ;
                i++;
            }
            ViewBag.People = personViews;


            ViewBag.Team = TeamRepository.Get();
            return View();
        }
        public JsonResult GetEvents()
        {
            int vacationsCount = Vacationrepository.Count();
              
            
            var events = new List<CalendarEventy>();
            List<Vacation> vacations = new List<Vacation>();
            IEnumerable<Person> people = PersonRepository.IncludeGet(p=>p.Team);
            var colors = GetColors(people.Count());
            int i = 0;
            foreach (Person person in people)
            {
                vacations = Vacationrepository.Get(p => p.Peopleid == person.Id).ToList();

                DateTime start;
                DateTime end;
                var viewModel = new CalendarEventy();




                foreach (Vacation vacation in vacations)
                {
                    start = vacation.FirstDate;
                    end = vacation.SecontDate;
                    events.Add(new CalendarEventy()
                    {
                        Id = vacation.Id,
                        allDay = true,
                        title = "Vacation" + " " + person.LastName + " " + person.Name + " " + person.Team.TeamName,
                        start = start.ToString("yyyy-MM-dd"),
                        end = end.ToString("yyyy-MM-dd"),

                        backgroundColor = vacation.ConfirmedVacation ? colors[i] : "red"
                    });


                }
                i++; 
            }
            return Json(events.ToArray());
        }
        public JsonResult GetWeekend()
        {
            IEnumerable<Weekend> Weekends = WeekendRepository.Get();
            List<DateForVacationAll> dates = new List<DateForVacationAll>();
            foreach (Weekend weekend in Weekends)
            {
                for (DateTime date = weekend.startDate; date <= weekend.EndDate;)
                {
                    dates.Add(new DateForVacationAll
                    {
                        Id = Guid.NewGuid(),
                        Date = date.ToString("yyyy-MM-dd")
                    });
                    date=date.AddDays(1);
                }
            }

            return Json(dates.ToArray());
        }
        public void ChangeDateVacation([FromBody] CalendarEventy request)
        {
         
          
            string start = request.start.Substring(0 , 10).Replace("-","/");
            string end = request.end.Substring(0, 10).Replace("-", "/");

Vacation/Workers/Controllers/TeamController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Drawing;
using System.Linq;
using System.Threading.Tasks;
using DataAccessLayer.Models;
using DataAccessLayer.Repository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Workers.Models;
using Workers.Models_View;

namespace Workers.Controllers
{
/*    [Authorize]*/
    public class TeamController : Controller
    {
        public IEFGenericRepository<Team> TeamRepository { get; set;}

        public IEFGenericRepository<Person> Personrepository { get; set; }

        public IEFGenericRepository<Vacation> Vacationrepository { get; set; }
        public TeamController(IEFGenericRepository<Person> personrepository,IEFGenericRepository<Team> teamRepository,IEFGenericRepository<Vacation> vacationRepository)
        {
            Personrepository = personrepository;
            TeamRepository = teamRepository;
            Vacationrepository = vacationRepository;

        }
        [Route("/{TeamName}/{TeamId}")]
        public IActionResult TeamIndex(Guid TeamId,string TeamName)
        {
            ViewData["Message"] = "Your Team page.";
            ViewData["TeamName"] = TeamName;
            ViewBag.TeamId = TeamId;
            return View(Personrepository.Get(person=>person.TeamId== TeamId));
        }
        [Route("{TeamName}")]
        [Authorize(Roles = "admin")]
        public IActionResult TeamDelete(Guid TeamId)
        {
            Team team = TeamRepository.FindById(x=>x.Id==TeamId);
            TeamRepository.Remove(team);
             return Redirect("~/");
        }
        [Route("Team/ShowvacationTeam/{TeamId}")]
        public IActionResult ShowvacationTeam(Guid TeamId)
        {

            return View();
        }
        [Route("Team/GetEvents/{TeamId}")]
        public JsonResult GetEvents(Guid TeamId)
        {
            int vacationsCount = Vacationrepository.Count();
            int i = 1;
            var colors = new List<string>();
                int integerRedValue = 8;
                int integerGreenValue = 95;
                int integerBlueValue = 52;
            for (int j = 0; j < vacationsCount; j++)
            {
                string hexValue ='#'+ integerRedValue.ToString("X2") + integerGreenValue.ToString("X2") + integerBlueValue.ToString("X2");
                colors.Add(hexValue);
                integerBlueValue += 24;
                integerGreenValue += 14;
                integerRedValue += 41;
                if (integerBlueValue > 255)
                    integerBlueValue = 0;
                if (integerGreenValue > 255)
                    integerGreenValue = 0;
                if (integerRedValue > 255)
                    integerRedValue = 0;
            }
            var events = new List<CalendarEventy>();
            List<Vacation> vacations = new List<Vacation>();
            IEnumerable<Person> people = Personrepository.Get(p => p.TeamId == TeamId).ToList();
            foreach (Person person in people)
            { 
                vacations = Vacationrepository.Get(p => p.Peopleid == person.Id).ToList();
                DateTime start;
                DateTime end;
                var viewModel = new CalendarEventy();
                foreach (Vacation vacation in vacations)
                {
                    start = vacation.FirstDate;
                    end = vacation.SecontDate;
                    events.Add(new CalendarEventy()
                    {
                        Id=Guid.NewGuid(),
                        allDay=true,
                        title = "Vacation"+" "+ person.LastName+" "+person.Name,
                        start = start.ToString("yyyy-MM-dd"),
                        end = end.ToString("yyyy-MM-dd"),
                        backgroundColor = colors[i]
                    });
                }
                  i++;
            }
           return Json(events.ToArray());  
        }
    }
}

Vacation/Workers/Views/Home/AddnewTeam.cshtml
@model DataAccessLayer.Models.Team
@{
    ViewData["Title"] = "About";
}
@using (Html.BeginForm("CreatenewTeam", "Home", FormMethod.Post))
{
    <div class="col">
        <label>Add new Team</label>
        @Html.TextBoxFor(m => m.TeamName, new {@class="form-control"})
        @*//<input type="text" name="TeamName" placeholder="Team NAme" class="form-control" />*@
    </div>
    <div class="col">
        <h2>Minimum count workers</h2>
        @Html.TextBoxFor(m => m.MinNumberWorkers, new { @class  = "form-control", @type = "number",@min=0,@max=10 })
        @*<input type="number" class="form-control" name="MinNumberWorkers">*@
    </div>
    <div style="margin:10px 0px " class=" col">
         <button type="submit" class=" btn btn-primary btn-lg btn-block">Add</button>
    </div>
}

Vacation/Workers/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Vacation/Workers/Views/Home/Index.cshtml
@model IEnumerable<DataAccessLayer.Models.Team>

@{
    ViewData["Title"] = "Home Page";
}

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>

    <div class="container">


        <div class="row">
            <div>
                <h2>Team</h2>
                @foreach (var team in Model)
                {
                    <li><a asp-area="" asp-controller="Team" asp-action="TeamIndex" asp-route-TeamName="@team.TeamName" asp-route-TeamId="@team.Id">@team.TeamName</a> </li>
                }
            </div>
        </div>
        <div class="row">
            <div class="col-md-2" >
                @if (@User.FindFirst(claim => claim.Type == System.Security.Claims.ClaimTypes.Role)?.Value == "admin")
                {
                    <a asp-area="" asp-controller="Home" asp-action="AddnewTeam">

                        <button type="button" class="btn btn-primary">
                            Add new Team
                        </button>

                    </a>
                 }
            </div>
            <div class="col-md-2" >
                <a asp-area="" asp-controller="Home" asp-action="ShowVacationAll">
                    <button class="btn btn-primary">
                        Show Vacation
                    </button>
                </a>
            </div>

        </div>
    </div>

Vacation/Workers/Views/Home/Mydata.cshtml
@*@model DataAccessLayer.Models.Person
{
   ViewData["Title"] = "Mydata";
}*@

<h2>My data</h2>
<table class="table table-dark">
    <thead>
    <th scope="col">Name </th>
    <th scope="col">Surname </th>
    <th scope="col">Days </th>
    <th scope="col">Team </th>
    <th scope="col"></th>
    <th scope="col"></th>
    <th scope="col"></th>

    </thead>
    <tbody>


        <tr>
            <th scope="row">@Model.Name </th>
            <th scope="row">@Model.LastName </th>
            <th scope="row">@Model.Days </th>
            @if (Model.Team == null)
            {
                <th scope="row"> </th>
            }
            else
            {
                <th scope="row"> @Model.Team.TeamName </th>
            }
            <th scope="row"><a asp-area="" asp-controller="Vacation" asp-action="ShowVacation" asp-route-personId="@Model.Id"><button type="button" class="btn btn-secondary btn-sm" style="margin:0,20px; ">Vacation</button></a></th>
   
            
                <th scope="row"><a asp-area="Person" asp-controller="Person" asp-action="ChangePerson" asp-route-personId="@Model.Id"><button type="button" class="btn btn-secondary btn-sm" style="margin:0,20px; ">Change</button></a></th>
                @*<th scope="row"><a asp-area="Person" asp-controller="Person" asp-action="DeletePerson" asp-route-personId="@Model.Id"><button type="button" class="btn btn-secondary btn-sm" style="margin:0,20px; ">Delete</button></a></th>*@
            
        </tr>

    </tbody>
</table>

Vacation/Workers/Views/Home/NewVacation.cshtml
@model IEnumerable<Workers.Models_View.NewVacationAdmin>
@{
    ViewData["Title"] = "NewVacation";
}

<h2>NewVacation</h2>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="js/jquery-1.9.1.min.js" type="text/javascript"></script>
    <script src="js/daypilot-all.min.js" type="text/javascript"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.0.1/fullcalendar.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
    <link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css" />
    <link type="text/css" rel="stylesheet" href="themes/month_white.css" />
    <script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.7.0/moment.min.js" type="text/javascript"></script>
</head>

<div class="row">
    <table class="table table-dark">
        <thead>
        <th scope="col">Start Date </th>
        <th scope="col">Finish Date </th>
        <th scope="col">Days </th>
        <th scope="col">First Name </th>
        <th scope="col">Last Name </th>
        <th scope="col"></th>
        <th scope="col"></th>



        </thead>
        <tbody>

            @foreach (var vacation in Model)
            {

            <tr>
                <th scope="row">@vacation.FirstName</th>
                <th scope="row">@vacation.LastName</th>
                <th scope="row">@vacation.StartDate.ToString("yyyy-MM-dd") </th>
                <th scope="row">@vacation.FinishDate.ToString("yyyy-MM-dd") </th>
                <th scope="row">@vacation.Days </th>


                @if (@User.FindFirst(claim => claim.Type == System.Security.Claims.ClaimTypes.Role)?.Value == "admin")
                {
                    <th scope="row"><a asp-area="" asp-controller="Vacation" asp-action="DeleteVacation" asp-route-vacationID="@vacation.Id" asp-route-personId="@vacation.PersonId"><button type="button" class="btn btn-secondary btn-sm" style="margin:0,20px; ">Delete</button></a></th>
                    <th scope="row">
                        <div class="col-md-2">
                            <a asp-area="" asp-controller="Vacation" asp-action="Confirm"  asp-route-vacationID="@vacation.Id"><button type="button" class="btn btn-secondary btn-sm" style="margin:0,20px; ">Confirm</button></a>
                        </div>
                    </th>
                }
            </tr>
            }
        </tbody>
    </table>
</div>
<div class="row">
   
 
</div>

Vacation/Workers/Views/Home/NextYear.cshtml
@model IEnumerable<DataAccessLayer.Models.Weekend>
@{
    ViewData["Title"] = "NextYear";
}

<h2> Change weekend</h2>
<table class="table table-dark">
    <thead>
    <th scope="col">Name </th>
    <th scope="col">Start date </th>
    <th scope="col">Finish date </th>
    <th scope="col"></th>
    <th scope="col"></th>
    <th scope="col"></th>

    </thead>
    <tbody>

        @foreach (var weekend in Model)
        {

            <tr>
                <th scope="row">@weekend.Name </th>
                <th scope="row">@weekend.startDate.ToString("yyyy-MM-dd") </th>
                <th scope="row">@weekend.EndDate.ToString("yyyy-MM-dd") </th>
               <th scope="row"><a asp-controller="Holidays" asp-action="ChangeWeekend" asp-route-holidaysId="@weekend.Id"><button type="button" class="btn btn-secondary btn-sm" style="margin:0,20px; ">Change</button></a></th>
                <th scope="row"><a asp-area="" asp-controller="Person" asp-action="DeletePerson" asp-route-holidaysId="@weekend.Id"><button type="button" class="btn btn-secondary btn-sm" style="margin:0,20px; ">Delete</button></a></th>
              
            </tr>
        }
    </tbody>
</table>

Vacation/Workers/Views/Home/Workers.cshtml
@model IEnumerable<DataAccessLayer.Models.Person>
@{
    ViewData["Title"] = "Workers";
}
<h2>@ViewData["Title"]</h2>
@*<h3>@ViewData["Message"]</h3>*@
<table class="table table-dark">
    <thead>
    <th scope="col">Name </th>
    <th scope="col">Surname </th>
    <th scope="col">Days </th>
    <th scope="col">Team </th>
    <th scope="col"></th>
    <th scope="col"></th>
    <th scope="col"></th>

    </thead>
    <tbody>

        @foreach (var person in Model)
        {

        <tr>
            <th scope="row">@person.Name </th>
            <th scope="row">@person.LastName </th>
            <th scope="row">@person.Days </th>
            @if (person.Team == null)
            {
                <th scope="row"> </th>
            }
            else
            {
                <th scope="row"> @person.Team.TeamName </th>

            } @if (@User.FindFirst(claim => claim.Type == System.Security.Claims.ClaimTypes.Role)?.Value == "admin")
            {
                <th scope="row"><a asp-area="" asp-controller="Vacation" asp-action="ShowVacation" asp-route-personId="@person.Id"><button type="button" class="btn btn-secondary btn-sm" style="margin:0,20px; ">Vacation</button></a></th>

                <th scope="row"><a asp-area="Person" asp-controller="Person" asp-action="ChangePerson" asp-route-personId="@person.Id"><button type="button" class="btn btn-secondary btn-sm" style="margin:0,20px; ">Change</button></a></th>
                <th scope="row"><a asp-area="Person" asp-controller="Person" asp-action="DeletePerson" asp-route-personId="@person.Id"><button type="button" class="btn btn-secondary btn-sm" style="margin:0,20px; ">Delete</button></a></th>
            }
        </tr>
        }
    </tbody>
</table>
<div class="row">
    <div class="col-md-2">
        @if (@User.FindFirst(claim => claim.Type == System.Security.Claims.ClaimTypes.Role)?.Value == "admin")
        {
            @if (@ViewBag.NextYear)
            {
                <a asp-action="NextYear" asp-controller="Home"><button class="btn btn-dark">Next Year</button></a>
            }
        }
    </div>
    <div class="col-md-2">
    @if (@User.FindFirst(claim => claim.Type == System.Security.Claims.ClaimTypes.Role)?.Value == "admin")
    {
       
            <a asp-action="CreatenewPerson" asp-controller="PersonController"><button class="btn btn-dark">Add person</button></a>
        
    }
    </div>
    <div class="col-md-2">
        @if (@User.FindFirst(claim => claim.Type == System.Security.Claims.ClaimTypes.Role)?.Value == "admin")
        {
            <a asp-area="" asp-controller="Home" asp-action="AddnewTeam"><button class="btn btn-dark">Add team</button></a>

        }
    </div>
</div>